### PR TITLE
Introduce AsyncPoll

### PR DESCRIPTION
**Pull request by jano**

### CODE REVIEW

**Comment by jano** [comment]
Usage example:

```Hack
<?hh

include "AsyncCondition.php";
include "AsyncConditionNode.php";
include "AsyncPoll.php";

async function foo() {
  $awaitables = array(
    async { return 0; },
    async { await RescheduleWaitHandle::create(0, 1); return 1; },
    async { return 2; },
    async { await RescheduleWaitHandle::create(0, 0); return 3; },
  );

  $poll = \HH\Asio\AsyncPoll::from($awaitables);
  foreach ($poll await as $item) {
    var_dump($item);
  }
}

foo()->join();
```

**Comment by fredemmott** [comment]
Please extend the README.md

**Comment by fredemmott** [comment]
ping

**Comment by jano** [comment]
Feel free to use this PR as an example of how to implement asynchronous polling. We will eventually land a stable version of this to the HHVM repo.

**Pull request closed without merging**
